### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by mellinger** [bobdavies2000/OpenCVB#2]
Hi! First off, thank you for this amazing endeavor, it looks like a peerless and incredible resource for learning. I'm excited to play around and apply it to my own education. 

Unfortunately I've got some build errors (screenshot attached) -- any ideas? 

Thanks!
Max
<img width="1478" alt="Screenshot 2021-02-04 214644" src="https://user-images.githubusercontent.com/812466/106994988-c2410980-6732-11eb-8f1c-946ec10cea63.png">

**Comment by bobdavies2000** [comment]
Did you set "Any CPU"?  It should be 64-bit.  The install is complicated
but I don't see how that could have happened.  Did you run the
"PrepareTree.bat" and build OpenCV, Librealsense, and Kinect4Azure before
building OpenCVB?

**Comment by mellinger** [comment]
I set it to 64-bit explicitly but the errors persists. I ran the .bat and built OpenCV and K4A, is Librealsense a hard requirement if you aren't using those cameras?

**Comment by bobdavies2000** [comment]
Mellinger - the AnyCPU configuration was automatically created when I was
testing some packages that were later removed.  It shouldn't have been
there at all.  Microsoft makes it the default for fresh Github downloads.
There is only an x64 configuration now and if you sync up with the latest
version, it is the only version that will show up.  Thanks for the
insight.  Very useful.

Building librealsense is currently a requirement as the OpenGL examples all
use the OpenGL and the include files there.  The resulting OpenGL examples
all work with the K4A.

Once you build librealsense, everything should build.  Make sure that you
set OpenCVB to be the "Startup Project" before hitting the "Start" button.
It is mentioned in the install instructions.

K4A is the best camera available but the Intel RealSense D455 is a close
second.  Please let me know if you continue to hit problems as these are
useful insights.

Bob Davies

**Comment by bobdavies2000** [comment]
Mellinger - I should have caught the reference to SkiaSharp in your first
email.  You downloaded the Version 1.0 release from 17 days ago.  I have
updated the instructions for releases here:

https://github.com/bobdavies2000/OpenCVB/releases/tag/version

I only did a release to familiarize myself with GitHub's process and the
SkiaSharp reference was the source of a couple problems.  It added a
configuration for AnyCPU when everything in OpenCVB is x64.  SkiaSharp has
since been removed as has the AnyCPU configuration.  The versioning system
doesn't seem like a good fit for a project like OpenCVB.  The repository is
the release.

Bob

>

**Comment by mellinger** [comment]
Thank you!
